# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
url     : https://philip.wang
baseurl : ""  # leave empty for GitHub Pages or specify your subpath
title   : WHO AM I
subtitle: "Interacting Parts | Emergence | Feedback Loop | Non-Linear | Self-Organizing"
name    : "Philip Wang"
description: > # this means to ignore newlines until "Language & timezone"
  Your Site Description
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Navigation
nav:
  - title: "首页"
    url: /
  - title: "关于"
    url: /about/
  - title: "归档"
    url: /year-archive/
  - title: "标签"
    url: /tags/


## => Language and Timezone
##############################
locale: "en-US" # en-US, zh-CN, etc.
timezone: Asia/Shanghai


## => Author and Social
##############################
author:
  name      : "Philip Wang"
  avatar    : "https://via.placeholder.com/150" # path of avatar image or placeholder
  bio       : "Agile Coach@odd-e."
  location  : "China"
  email     : philip.wang@odd-e.com
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:philip.wang@odd-e.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://philip.wang"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wjmmx"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/philipwj/"


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: wjmmx/wjmmx.github.io
repository_tree: master


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## Reading time
words_per_minute: 200

## Table of contents
toc: true
toc_label: "Contents"
toc_icon: "cog"

## Breadcrumbs
breadcrumbs: true  # true, false (default)
breadcrumb_home_label: "Home"
breadcrumb_separator: "/"

## Search
search: true
search_full_content: true # false (default)


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need



## => Comments
##############################
comments:
  provider: gitalk # false (default), "disqus", "gitalk", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : 11d04aca02ecf0f79878
    clientSecret: ebe4fe1028b954b579df422800467bf79c35ed9b
    repository  : wjmmx.github.io
    owner       : wjmmx
    admin: wjmmx
      # - your GitHub Id




## => Analytics
##############################
analytics:
  provider: google # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : UA-134620711-1 # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Archive
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  # - scope:
  #     path: "_posts"
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  # 404.html
  - scope:
      path: "404.html"
    values:
      layout: single
      title: "Page Not Found"
      excerpt: "Page not found. Your pixels are in another canvas."
      sitemap: false
  # about.md
  - scope:
      path: "about.md"
    values:
      layout: single
      author_profile: true

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

collections:
  tags:
    output: true
    permalink: /tags/:name/